---
name: Bug Report
description: Is something not working as expected? Submit a bug.
title: "[BUG] REPLACE WITH A SHORT DESCRIPTION"
labels: [type/bug, status/needs-triage]
assignees:
  - tenthirtyam
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a [Code of Conduct](https://github.com/vmware/photon-packer-templates/blob/master/CODE_OF_CONDUCT.md) that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: input
    id: version-hypervisor
    attributes:
      label: Hypervisor
      description: Please provide the hypervisor and version.
      placeholder: VMware Fusion 12
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please provide the Packer host operating system.
      placeholder: macOS 12 (Intel)
    validations:
      required: true
  - type: input
    id: version-packer
    attributes:
      label: HashiCorp Packer
      description: Please provide the HashiCorp Packer version.
      placeholder: 1.8.3
    validations:
      required: true
  - type: input
    id: version-packer-vmware
    attributes:
      label: HashiCorp Packer Plugin for VMware
      description: Please provide the HashiCorp Packer Plugin for VMware version.
      placeholder: 1.0.7
    validations:
      required: false
  - type: input
    id: version-packer-virtualbox
    attributes:
      label: HashiCorp Packer Plugin for Virtualbox
      description: Please provide the HashiCorp Packer Plugin for Virtualbox version.
      placeholder: 1.0.4
    validations:
      required: false
  - type: input
    id: version-vagrant
    attributes:
      label: HashiCorp Vagrant
      description: Please provide the HashiCorp Vagrant version. `vagrant version`
      placeholder: 2.3.1
    validations:
      required: true
  - type: input
    id: version-vagrant-vmware-utility
    attributes:
      label: HashiCorp Vagrant VMware Utility
      description: Please provide the HashiCorp Vagrant VMware Utility version. 
      placeholder: 1.0.21
    validations:
      required: false
  - type: input
    id: version-vagrant-vmware-plugin
    attributes:
      label: HashiCorp Vagrant plugin for VMware
      description: Please provide the HashiCorp Vagrant plugin for VMware version. `vagrant plugin list`
      placeholder: 3.0.1
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please add any information you can provide about the environment.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What is it you expected to happen?
        This should be a description of how the functionality you tried to use is supposed to work.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened that's different from the expected behavior?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Fragments and Files
      description:  |
        Please include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the [Gist](https://gist.github.com/) of the log or use the [GitHub detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshots of the issue, if applicable.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide a code repository, gist, code snippet, sample files, screenshots, or anything else you think will aid in reproducing the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Community Note
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
